### PR TITLE
Nicola/rewards

### PR DESCRIPTION
**Pull request by nicolaloi**
add more metrics/rewards + history_actions

### CODE REVIEW

**Comment by alezana** [comment]
@nicolaloi thanks for the PR. 

A few things I'd change:
- Shall we have a GokartActions class in trajectory style? I would prefer to have a dataclass with fields' names such that one can access them not by relying on positional encoding in the array. (This favors readibility and extendibility, e.g., when we add the mechanical brake for example)
- To stay closer to the centerline why don't we just use a quadratic penalty if we get too close? The offroad with boolean feels a bit odd, do you terminate the episode if you are out? Do you wanna learn maneuvers when you violate this "constraint"?

**Comment by nicolaloi** [comment]
- ok instead of a matrix I will add an action class to sim_trajectory
- the behavior is the same as before, the episode terminates if a corner of the kart is out of bounds. Now I have just added an extra negative reward like a soft constraint, at every step where gokart is closer than 0.2 m from the bounds there is a constant reward penalty, but the episode does not terminate. I can change it to a quadratic penalty if it gets too close to the bounds, `penalty = -k(safety_margin-min(safety_margin,dist_to_bound))^2`

**Comment by nicolaloi** [comment]
@alezana updated

**Comment by alezana** [comment]
@nicolaloi thx! I would still be in favor of a small round of clean up for simplicity and interpretability....

For example, look at this plot:
image

can you tell me anything about the behavior of the kart? no unless you start reverse calculating stuff digging in code to see the parameters etc.
So, what about something like GokartDistanceToBoundsMetric actually returns (indeed) the min distance to the boundaries in [m], no weird scaling, squared stuff, additional_offroad_reward etc, at maximum we can cap it beyond a certain value. I know that coming from a control/optimization background the temptation to write squared rewards and so on is strong (I have it myself), but in general this is not desirable in RL, ideally you want the reward as close as possible to the actual task. 

The only thing that maybe I would add is the option to cap the progress so that to have a safer behavior we can simply specify:
- cap-progress to max desired velocity
- reward for keeping distance to the barriers
- minimize control effort/rate 

Simple, clean, easy to readjust in a "interpretable" manner

**Comment by nicolaloi** [comment]
The extra reward offset is an optimization to avoid calling the GokartOffroadMetric if you want to penalize pure offroad behaviors too. These bounds/offroad metrics are really heavy in computations and their use is noticeable in the final training time, so you could call one metric to achieve both penalties. I would put the default extra_offroad argument to 0 but I would leave it if someone wants to experiment adding the proper offroad metric without having to slow down the training.

I have changed the quadratic penalty but to me it makes sense to penalize more a displacement of 1 cm towards the bounds when you are very close to the bounds, compared to when you are some tens of centimeters away from them.

**Comment by alezana** [comment]
@nicolaloi I refactored a bit with the following in mind:

We want metrics to be clearly defined with a "static" definition related to task accomplishment or physical quantities ( distance to the barriers, is_offroad, is_overlap,....). This helps also to compare the resulting behaviors of a certain training. The reward can be instead some funky transform and combination of metrics in a bid to achieve the desired behavior.

Hence, the following main modifications:
- metrics registry cannot be updated "on the fly" by changing the metric associated to a certain str
- introduction of LinearTransformedReward where you can specify optionally an additional transform to apply to a certain metric (by default identity, in principle any map Array -> Array)

**Pull request merged**
